### ISSUE TITLE
question about Single-utterance dynamic pseudo labeling (SDPL)

### ISSUE THREAD

**Issue by 1633347510** [DanielLin94144/Test-time-adaptation-ASR-SUTA#1]
hello!  I am interested in the implement details of the Single-utterance dynamic pseudo labeling (SDPL) method, could you tell me how to do it?  Thank you very much for your efforts on ASR tasks.

**Comment by DanielLin94144** [comment]
Hi, thanks for your question. The SDPL method is implemented in [main_SDPL.py](https://github.com/DanielLin94144/Test-time-adaptation-ASR-SUTA/blob/main/main_SDPL.py#L194).

**Comment by 1633347510** [comment]
> Hi, thanks for your question. The SDPL method is implemented in [main_SDPL.py](https://github.com/DanielLin94144/Test-time-adaptation-ASR-SUTA/blob/main/main_SDPL.py#L194).

thank you for your reply!

**Comment by 1633347510** [comment]
i am sorry to bother you again. it is difficult for me to totally understand the coding. I'm curious to know whether any labeled data was used in the SDPL methods for adapt the source model. and for SDPL, is it the same with SUTA: for each utterance, starting from the original weights of source ASR model.
