### ISSUE TITLE
more questions about SDPL

### ISSUE THREAD

**Issue by 1633347510** [DanielLin94144/Test-time-adaptation-ASR-SUTA#2]
i am sorry to bother you again. it is difficult for me to totally understand the coding. I'm curious to know whether any labeled data was used in the SDPL methods for adapt the source model. and for SDPL, is it the same with SUTA: for each utterance, starting from the original weights of source ASR model.

**Comment by DanielLin94144** [comment]
@1633347510 The Single-utterance dynamic Pseudo Labeling (SDPL) is a simple pseudo-labeling method using a single utterance as SUTA. The source ASR is the same. The only difference is the **training objective**. SDPL uses CTC loss with the greedy decoding pseudo label to update source ASR parameters, but SUTA uses our proposed update algorithm. Noting that we update the pseudo label every step, so we called it a **dynamic** pseudo labeling.
